apiVersion: apps/v1
kind: Deployment
metadata:
  name: fuelconsumption-app
  labels:
    app: fuelconsumption-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fuelconsumption-app
  template:
    metadata:
      labels:
        app: fuelconsumption-app
    spec:
      containers:
        - name: fuelconsumption-app
          image: taifjalo1/otp2-fuel-calculator-localization:latest
          imagePullPolicy: Never   # use Never for local images
          env:
            - name: DISPLAY
              value: "host.minikube.internal:0.0"
            - name: JAVA_TOOL_OPTIONS
              value: "-Dprism.order=sw"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"